---
name: Run CI checks

on:
  pull_request:
    types: "**"
    branches: "**"
  pull_request_review:
    types: "**"
    branches: "**"
jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Check for Merge Conflicts
      run: |
          git fetch origin
          git checkout -b ${{ github.event.pull_request.head.ref }} origin/${{ github.event.pull_request.base.ref }}
          git merge --no-commit --no-ff ${{ github.event.pull_request.head.sha }}
          if git diff --name-only --diff-filter=U; then
            echo "Merge conflicts detected."
            # Add steps to handle merge conflicts here
            exit 1
          fi
    - name: Check status
      if: steps.merge_conflict_check.outcome == 'failure'
      run: |
          echo "This has a merge conflict."
          
